[tools]
rojo = "rojo-rbx/rojo@7.4.4"

luau-lsp = "JohnnyMorganz/luau-lsp@1.37.0"
selene = "Kampfkarren/selene@0.27.1"
stylua = "johnnymorganz/stylua@2.0.2"

wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"